### ISSUE TITLE
Your Manifest file ScreenSaver.yaml has the wrong Required API version for Playnite Addon Database

### ISSUE THREAD

**Issue by 0-Hex** [cnapolit/ScreenSaver#33]
Just thought Id let you know you set the wrong RequiredApiVersion in your manifest file so currently no one can install from the Playnite Add-ons menu. You have it set to 9.0.0 it should be set to I believe its 6.2.0 for P9 or 6.3.0 for P10.

**Comment by cnapolit** [comment]
Thanks for pointing it out. Fixed!
