### ISSUE TITLE
Installed ScreenSaver extension and it's not working.

### ISSUE THREAD

**Issue by limodual** [cnapolit/ScreenSaver#66]
Recently installed ScreenSaver extension in Playnite 10.8, but it's not showing any screen saver and I checked the extension settings and seems everything is fine. I really wanted to try this extension please someone help me.

**Comment by cnapolit** [comment]
Anything in the 'extensions.log' file? It can be found in the same directory as the playnite exe files.
Is Windows Media Player installed? Some .NET tools have weird dependencies on things like WMP.

**Comment by limodual** [comment]
I don't actually needed to use the preview (but tested to see if that works at least). I just want the Screen saver with possibly a video. Hope you fix it somehow :)

**Comment by cnapolit** [comment]
Sounds like a polling issue. Try disconnecting all devices (particularly controllers, keyboards, mice).
If that works, then one of your devices is faulty and sending inputs when it shouldn't.

Otherwise, I may need to add some log statements to better figure out what's happening.

**Comment by limodual** [comment]
Tried removing all devices but still it's not working. This time I tried going to Menu>Extensions>ScreenSaver>Start ScreenSaver, but still not worked, maybe it's not related to the devices which are not faulty (they're new).

**Comment by limodual** [comment]
Bro, is there any some kind of prerequisite that is needed for this extension to work apart from Windows media player and .NET Firmwork? It seems so many people got working this extension easily but mine not at all working.

**Comment by cnapolit** [comment]
One last thing you could do is restart the app and immediately checking the logs after.
We might not have seen anything before if something is failing early on when the plugin is first loaded.

The next step for me, if that doesn't yield any info, would be to create a version of the plugin that has a lot more logging during input polling and when the plugin attempts to play.

As a side note, if you're using any groups, make sure the group has games in it.

**Comment by limodual** [comment]
Sorry for the late reply but I really don't know how to access extension logs like you mentioned before, I didn't found it in the Playnite's folder.

**Comment by cnapolit** [comment]
All good, I'll be going on vacation at the end of the week, so I'll have more time them to look into this issue.
If you're willing, we could hop on a discord call or something around then to figure this out.

**Comment by cnapolit** [comment]
Since there's been no updates, I'll close this issue.

Some parting suggestions: 

You mentioned the video not displaying. Ensure the settings are configured to display games, even when the video is missing. If it can't find any video files, then it won't display any games if it's to skip them.

Ensure there are no invalid files within the extra metadata folder. an issue cropped on on the sounds plugin where it wouldn't play if it attempted to use a bad file.

If you're willing to debug further, feel free to reach out.

**Comment by limodual** [comment]
Hey, I decided to not to have screen saver for simplicity and keep the app light as possible and also it stutters a bit when the extension is installed. Maybe I will try it in the future when the extension get's optimized and of course when it starts to work on my PC somehow. But thanks for offering your support all along.
