### ISSUE TITLE
Change logo size, position and margins

### ISSUE THREAD

**Issue by grogfella** [cnapolit/ScreenSaver#75]
Exactly what it says on the tin.

In my use case of using Playnite with a CRT television, using a screensaver is absolutely essential to reduce burn-in, but thanks to the TV's inherent low resolution and significant overscan, many logos appear small and are cut off at the corners. Therefore it would be very useful if I could specify how much padding from the corners should be applied to the logos, how large the logos should appear, and in which area of the screen they should appead.

**Comment by cnapolit** [comment]
Hoping to add custom layouts & more settings to help with stuff like this.
Focusing on pushing out a release for the Sounds plugin, so it won't be anytime soon.
