### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by qu8tis** [cnapolit/ScreenSaver#76]
I have been using version 2.0.0 and until today it was working, when I updated to 2.0.5 the plugin stopped working.
Just uninstalling it and going back to 2.0.0 the screensaver works again.

**Comment by cnapolit** [comment]
What version of Playnite are you using? Only thing I could think is one of the methods it will rely on in that newer release doesn't exist.

I'd check the log files (located in the same directory as the playnite library folder) to see if there are any note worthy messages coming from the plugin.

**Comment by cnapolit** [comment]
closing due to age of issue
