### ISSUE TITLE
Screensaver dismisses immediately if certain controllers are connected

### ISSUE THREAD

**Issue by grogfella** [cnapolit/ScreenSaver#79]
I'm using an 8bitdo wired controller with Playnite and this screensaver plugin, and whenever that controller is connected, the screensaver never starts.
This is not a problem with other Xbox controllers. Evidently as long as the controller is connected, it's always sending some kind of polling state change to the screensaver, dismissing it as soon as it starts.
I've tried to edit the screensaver code myself to resolve the issue, but so far I've come up blank and I'm hoping anyone else might know of a fix.

**Comment by cnapolit** [comment]
My guess is the packet number is changing constantly, even when there's no input:
https://github.com/cnapolit/ScreenSaver/blob/0b81444b7f3923417abd5732613c5334e8008618/Services/State/Poll/PollManager.cs#L238

Long term, it'll make sense to fix this by moving away from the input library this plugin uses in favor of the valve library that Playnite also uses.

Can't give any guarantee if/when I can get around to this.

**Comment by grogfella** [comment]
> My guess is the packet number is changing constantly, even when there's no input:
> 
> https://github.com/cnapolit/ScreenSaver/blob/0b81444b7f3923417abd5732613c5334e8008618/Services/State/Poll/PollManager.cs#L238
> 
> Long term, it'll make sense to fix this by moving away from the input library this plugin uses in favor of the valve library that Playnite also uses.
> 
> Can't give any guarantee if/when I can get around to this.

Thanks for the input, and of course massive thanks for creating this very useful plugin in the first place.
For the time being, I managed to build my own version with the relevant lines commented out. If I want to use these controllers, I'll let JoyToKey send a keyboard input to Playnite to dismiss the screensaver.

**Comment by cnapolit** [comment]
Glad you have a work-around! This controller framework I'm using will likely shift to what Playnite uses (for xinput support).
This issue will probably go away with that shift.
