### ISSUE TITLE
Screensaver not working for Videos

### ISSUE THREAD

**Issue by thisischrys** [cnapolit/ScreenSaver#81]
My screensaver only shows images.
If I enable "Skip games that don't have videos" I see "No games found while starting ScreenSaver" in the extensions log.

My videos are in paths like AppData\Roaming\Playnite\ExtraMetadata\games\010543e7-47c4-4edd-8da6-9720af9214a6\VideoTrailer.mp4 (and VideoMicrotrailer.mp4), is that right?

**Comment by cnapolit** [comment]
The path looks fine and the behavior makes sense if the plugin can't find the video file(s).
Maybe there is a filter applied to the games displayed.

I'd have to see settings options and the group info as well.

**Comment by thisischrys** [comment]
I had uninstalled the extension in the meanwhile.
I just reinstalled it to figure out what to reply to this, but now it's working.
Sweet!
